# .readthedocs.yaml
# Read the Docs configuration file
# Docs: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Which builder(s) to run. sphinx is the default.
build:
  os: ubuntu-24.04
  tools:
    python: "3.10" # or 3.11, whichever you support
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      - pip install -r docs/requirements.txt

# Tell RTD where your docs source is
sphinx:
  configuration: docs/source/conf.py

# If you want to upload coverage, badges, etc. Uncomment:
#  builder: html

# Optional: install your package in “editable” mode:
#  install:
#    - method: pip
#      path: .
#    - method: requirements
#      path: docs/requirements.txt

# Environment variables, if any
#env:
#  DJANGO_SETTINGS_MODULE: example.settings

formats:
  - html
# Optionally turn off PDF builds if you don’t need them:
#formats:
#  - html

