name: co2-emissions
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - lightgbm
  - xgboost
  - catboost
  - optuna
  - shap
  - pip:
      - jupyterlab
