# .readthedocs.yaml v2
# Read the Docs config file

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

# Install your docs dependencies first:
# (includes Sphinx, theme, and your package itself)
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install --upgrade pip setuptools wheel
      - pip install -r docs/requirements.txt

# Point to your Sphinx conf.py
sphinx:
  configuration: docs/source/conf.py

# No need to declare formats; RTD builds HTML by default.
